# THIS FILE STORES ALL CONFIGURATIONS 
# READ ONLY
WARNING: DO NOT CHANGE ANYTHING config.yaml  THIS FILE IS MEANT TO BE WRITTEN ONLY BY PROGRAM
info: TO CONFIGURE SETTINGS RUN THE setup.py file 

# specify full path if not in current working directory

user_name: AAHNIK DAW
auth: ~auth

# INSIDE THE ~auth.txt file put the following !
# sender's email i.e from email in first line
# device authentication key / password in second line

use: defaults

#############################################################

pull_data_from: data.cs

defaults:
  compose: compose.txt
  use_engine: text_to_html.py
  html: compose.html
  assets: /assets
  connection: tls

use_template: default

# CORRUPTION IN THIS FILE MAY LEAD TO UNINTENDED CONSEQUENCES

# AAHNIK 2020 