# THIS FILE STORES ALL CONFIGURATIONS 
# DO NOT CHANGE WITHOUT PROPER KNOWLEDGE

user_name: youremailhere@gmail.com
auth_code: auth_code_here

use: defaults

# specify full path if not in current working directory

pull_data_from: data.cs

defaults:
  compose: compose.txt
  use_engine: text_to_html.py
  html: compose.html
  assets: /assets
  connection: tls

use_template: default

# CORRUPTION IN THIS FILE MAY LEAD TO UNINTENDED CONSEQUENCES


# AAHNIK 2020 