# THIS FILE STORES ALL CONFIGURATIONS 
WARNING: DO NOT CHANGE config.yaml WITHOUT PROPER KNOWLEDGE

# specify full path if not in current working directory

user_name: aahnikdaw@gmail.com
auth_code: ~auth


use: defaults

#############################################################

pull_data_from: data.cs

defaults:
  compose: compose.txt
  use_engine: text_to_html.py
  html: compose.html
  assets: /assets
  connection: tls

use_template: default

# CORRUPTION IN THIS FILE MAY LEAD TO UNINTENDED CONSEQUENCES


# AAHNIK 2020 