# THIS FILE STORES ALL CONFIGURATIONS 
# READ ONLY
WARNING: DO NOT CHANGE ANYTHING config.yaml  THIS FILE IS MEANT TO BE WRITTEN ONLY BY PROGRAM
info: TO CONFIGURE SETTINGS RUN THE setup.py file 

# specify full path if not in current working directory

sender_name: AAHNIK DAW
auth: ~auth.txt

# INSIDE THE ~auth.txt file put the following !
# sender's email i.e from email in first line
# device authentication key / password in second line



#############################################################

pull_data_from: data.csv

compose: compose.txt

html: compose.html


# CORRUPTION IN THIS FILE MAY LEAD TO UNINTENDED CONSEQUENCES

# AAHNIK 2020 